CONFIG_STDOUT_CONSOLE=y

CONFIG_HEAP_MEM_POOL_SIZE=16384

CONFIG_I2C=y

CONFIG_DISPLAY=y
CONFIG_SSD1306=y

CONFIG_LOG=y
CONFIG_CHARACTER_FRAMEBUFFER=y

CONFIG_SENSOR=y

CONFIG_WATCHDOG=y

CONFIG_PWM=y

CONFIG_NVS=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y